### ISSUE TITLE
第8章 状態共有並行性

### ISSUE THREAD

**Issue by Altech** [wantedly/ctmcp-reading#10]
## 当日まで

* 各自読む
* できれば感想や疑問点をここに書くか、別イシューを紐付ける

## 当日

* 持ち回りで進める(45min) @Altech
* 疑問点や感想を事前のイシューで各自まとめて、ディスカッション(45min)
* 次の輪講の担当を決める

cc: @wantedly/ctmcp-readers @miliya612

**Comment by miliya612** [comment]
https://github.com/miliya612/ctmcp-reading/blob/master/08_shared_state_concurrency/memo.md

**Comment by Altech** [comment]
今回のディスカッションのピックアップ：最初のこの図が端的で素晴らしい

<img src=https://user-images.githubusercontent.com/1248994/57303278-f0398a00-7117-11e9-9694-b892a331f601.png width=500>


<img src=https://user-images.githubusercontent.com/1248994/57303096-8b7e2f80-7117-11e9-9ae6-dbbd3bca66b5.png width=500>

**Comment by Altech** [comment]
次：第9章 関係プログラミング #11
