### ISSUE TITLE
参加者募集（社内）

### ISSUE THREAD

**Issue by Altech** [wantedly/ctmcp-reading#2]
隔週で「コンピュータプログラミングの概念・技法・モデル」を読んでいく会を年始からやります。
下記のようなトピックを扱うので、参加する方はこちらのイシューにコメントお願いします。

オフィスに一個置いてあるので、どんな内容かみたい人はそれを見てみると良いかも。

【目次】 
* 導入 
　* 第1章 プログラミング概念入門 
* 第I部 一般的計算モデル 
　* 第2章 宣言的計算モデル 
　* 第3章 宣言的プログラミング技法 
　* 第4章 宣言的並行性 
　* 第5章 メッセージ伝達並行性 
　* 第6章 明示的状態 
　* 第7章 オブジェクト指向プログラミング 
　* 第8章 状態共有並行性 
　* 第9章 関係プログラミング 
* 第II部 特殊化された計算モデル 
　* 第10章 グラフィカルユーザインタフェースプログラミング (skip)
　* 第11章 分散プログラミング 
　* 第12章 制約プログラミング (skip)
* 第III部 意味 
　* 第13章 言語意味 (skip)

https://github.com/wantedly/ctmcp-reading/blob/master/README.md

@wantedly/developers

**Comment by intomyam** [comment]
🙋‍♂️

**Comment by nekootoko3** [comment]
🐈

**Comment by Oshiumi** [comment]
🙏

**Comment by hayaokimura** [comment]
参加したい

**Comment by ngtk** [comment]
✋

**Comment by munisystem** [comment]
👐

**Comment by s0hno** [comment]
:soccer:

**Comment by kdnk** [comment]
💪

**Comment by rerost** [comment]
👍

**Comment by south37** [comment]
🦊

**Comment by wakwak3125** [comment]
👓

**Comment by yu-ya4** [comment]
(ΦωΦ)

**Comment by Altech** [comment]
team を作りました！（Invite が行ってる？）以降これを使っていきます。
@wantedly/ctmcp-readers 

Amazon + Mercari で5冊ある(&既に持ってる人が3人いる)っぽいので、確実に日本語で読めるのは8人までですね。本の入手は各自にお任せします 💡
