### ISSUE TITLE
第一章 プログラミング概念入門 (1/8)

### ISSUE THREAD

**Issue by kdnk** [wantedly/ctmcp-reading#3]
## WHAT

**Comment by Altech** [comment]
20時からやります。一旦 Auditorium 会場にしましょう。今回は本なくて大丈夫です。

cc: @wantedly/ctmcp-readers

**Comment by Altech** [comment]
## やりたいこと（仮）

- みんなどのくらい準備してるかをまず確認して進める
- どういう風に進めるかを決める
- ＠Altech がまえがきを写す
- ＠Altech が Oz/Mozart でやりながら一章を進める
- 呼んだひとで疑問をいろいろ話し合う
- 練習問題を考える

**Comment by Altech** [comment]
## 現場

* 3割は読んでる

## どういう風に進めるかを決める

* 読んでる前提で進める
* 持ち回りで輪講(最初にやる)
* 疑問点や感想を事前のイシューで各自まとめて、読む(二番目)
  * ディスカッションしたいこととかもあれば
* 練習問題（これもやったものは事前にリポジトリに Push）(三番目)
  * 全部は難しそう
* 終わり際に次の準備

.

* Slack は作ろうと思ってる

**Comment by Altech** [comment]
お疲れ様でした！初回だったけど結構活発にディスカッションできて良かったですね。次回以降は内容がしっかりしてくるので読んだ前提で進めましょう。

**Comment by Altech** [comment]
👉 第二章 宣言的計算モデル (1/22) #4
