### ISSUE TITLE
第二章 宣言的計算モデル (1/22)

### ISSUE THREAD

**Issue by Altech** [wantedly/ctmcp-reading#4]
## 当日まで

* 各自読む
* できれば感想や疑問点をここに書くか、別イシューを紐付ける
* できれば練習問題も解く

## 当日

* 持ち回りで輪講(45min) @nekootoko3 
* 疑問点や感想を事前のイシューで各自まとめて、ディスカッション(30min)
* 練習問題（これもやったものは事前にリポジトリに Push or このイシューに紐付ける）(45min)
* 次の輪講の担当を決める

cc: @wantedly/ctmcp-readers @miliya612

**Comment by Altech** [comment]
2.2節まで読んだので個人的に大事だと思ったポイントメモ。

<details>
<summary>第二章：宣言的計算モデル</summary>

## 第二章：宣言的計算モデル

* プログラミングは以下の3つを含む。
	* 計算モデル
	* プログラミング技法＆設計原則 … based on each 計算モデル
	* プログラムについての推論技法
* 本章は、宣言的モデルを扱う
	* 親戚：関数型プログラミング、論理型プログラミング
		* なぜ関数型と呼ばないか？=> 部分値―まだ完全に値が定まらないような言語実体―も許すため。これは論理型プログラミングの考え方。

### 2.1 実用的プログラミング言語の定義

* プログラミング言語の定義 := 文法(syntax) + 意味論(semantics)
	* これはよくある枠組みなので覚えておくと良い
* 文法の定義
	* クラス分類：
		* 文脈自由文法 / 文脈依存文法
	* 文脈自由文法で定義して、後から制約を追加して文脈依存の定義にするのが理解しやすい
		* わかりやすい例：未定義の変数利用は不許可、というのは文脈自由文法では表現できないが、普通はまずは文脈自由文法で大枠を定義し、そういった制約は後から付与される
		* その他の制約：（曖昧性を解消するための）演算子の優先順位と結合性
* 核言語を用いる深い動機：現代の複雑なプログラミング言語―それはおそらく、複雑なプログラムをいかに構築するか？という問いに対する回答―を科学的に理解すること

> 思うに、ここまで複雑になった（現代のプログラミング）言語はある程度、成功している。複雑なプログラムをいかに構築するかということについての重要な側面のいくつかをモデル化しているからである。この意味で、こうした言語は人間の心が単に恣意的に構築したものではない。よって、こうした言語を科学的に理解したいと思う。すなわち、そのふるまいを、その底にある単純なモデルによって説明したいと思う。これが、核言語採用の裏にある深い動機である。  

* 私見：実用的プログラミング言語を学ぶ際も、言語の核となる部分とそれ以外に分けるのは割と理解が早くなり有用だと思う。それ以外というのは、lingistic abstraction / syntax sugar とか。
	* 例えば、手続き(Procedure)は関数(Function)の一般化だが、有用なので専用 syntax を用意する、など。
	* 概念的に新しいものを導入するのが linguistic abstraction で、ただ単に便利な記法を用意するのが syntax sugar. この二つの区別までできると、より解釈が早まるはず。
	* 普通こういったものは、最初は言語的な支援―使いやすくするための文法がない―状態から始まり、良いもので基本的なものだと認められたら、言語的な支援を得る。
* 意味…形式的意味と一口に行っても、実はいろいろあり、適不適がある。
	* 本書では主には操作的意味論を用いる。
		* 理由：正しさだけでなく、計算量についても正しい直観を与えたい

### 2.2 単一代入格納域(single-assignment store)

* 別名：宣言的変数、データフロー変数
	* これが本書で扱う基本的な「変数」
* その他のものとの対比：
	* A) Haskell などの関数型言語で現れる変数：値格納域
		* 単一代入格納域に一つだけ制約を加えたもの
			* 未束縛の変数を許さない、という制約
		* 単一代入格納域の方がちょっと一般化されている、と思うと良い。
	* B) Ruby などの手続き型言語でよく現れる変数：セル格納域
		* 書き換え可能
* 変数識別子(variable identifier)と格納域実体(store entity)を区別すること
	* これがないと、変数のシャドーイングなどの概念も理解しにくいはず
* その上で、環境(environment) という、変数識別子から格納域実体への写像が定義される
	* 変数を新たに定義したり束縛する行為は、環境の変更、となる
* 変数使用エラー―束縛する前に変数を使おうとすること―への対処可能性から、データフロー変数というものが導かれる
	* 関数型言語 => 未束縛の変数を許さないので、そういうことは起きない
		* ただし、これは並行性に関してできることを減らしていることが後々わかる
	* 手続き型言語 =>
		* C++ が採ってる undefined （振る舞い不定）はまじ最悪
		* 実行時エラーまたはコンパイルエラーは状況によっては良い
	* 宣言的モデル（Oz）はこのどれでもなく、ただ束縛を待つ！
		* これは並行性に対して威力を発揮する
		* 一方で、永遠に待つ（suspension）という新種のエラーを持ち込む
			* 良いデバッガはそれを見つけるべき（それは可能か？）
	* 私見：データフロー変数は良いものである一方で、実用的なプログラミング言語において基本要素とするかはかなり慎重な design が必要だろうと思う。
	* 私見：部分値、というのはあえて世に流通している抽象にに対応付けると ”future” とかになるのだけど、それらが後付け感があり元々あったものとどういった関係を持ち全体としてどういう体系なのかわからないのに対して、部分値-完全値という枠組みは非常に鮮やかではあるなと思った。
	* 私見：また、Wantedly がマイクロサービス・アーキテクチャで開発をする上で必要になるのは、主にデータフロー並行性であり、Golang のようなチャネルベースの並行プログラミングのモデル（本書で言う「メッセージ伝達並行性」）は本来的に自分たちが欲しているものより表現力が大き過ぎるなと思った。その上で現実的な選択肢としては、チャネルを元にデータフローベースの並行プログラミング（本書で言う「宣言的並行性」）のフレームワークを構築するのが良いのではないか、という感想を持った。ここは今後読み進めていく上で個人的な考察ポイントとしたい。
			* 直近の例：New scan API implementation https://github.com/wantedly/yashima/issues/5160

### 2.3 核言語

* 他の言語に関連付けて理解する場合、以下のようなポイントに留意すると良い。
	* 文(statement) を基本要素にしてる
		* 言語によっては、文ではなく式(expression)を基本要素とする
	* 手続き(procedure)を基本要素にしている
		* 言語によっては、手続きではなく関数(function)を基本要素とする
* Oz のレコード型は、多くのものを含むように強力に一般化されている
	* 一般的に、レコード型というとき key-value の連なりとなる
		* Oz のレコード型は、更に「ラベル」が付く
		* `foo(a: 1, b: 2)`
	* タプル… key がゼロ始まりの整数であるようなレコード
		* これ自体を基本要素とする言語もある
	* タプルでリストを定義できること
	* ※ こういう定義を見るときのポイント
		* なぜそういう定義にしたのか？を具体例と行き来して考える
		* 例えば、「ラベル」がなければ、リストは定義できない
			* リストは縦棒のタプルで作られるから `|(0: H 1: T)`  だから
			* `H | T` （なんか `H` と `T` をくっつけたもの）はどういう基本データ型があれば定義できるか？
* 手続きの定義 `proc { $ <y>1 <y>2 … }`  は少し癖があるから要説明かも
	* 値生成と変数束縛を分けるためにこうなっている
	* 例えば、JS の関数定義 `function foo(x, y)`と無名関数 `function (x,y)` の関係はどのように説明できるか？それを直接に構文に反映するならどうするか？を考えてみるとわかる

### 2.4 核言語の意味


* 静的スコープ（レキシカルスコープとも）という概念
	* 動的スコープを使っているよく知られた言語は Emacs Lisp
		* この範囲のおいては便利
	* ソフトウェアエンジニアリング的には、以下のような話に置き換えて理解できる
		* ダイナミックリンクライブラリのようなものをどう捉えるか？という話
		* あるいは逆に、Golang のようなワンバイナリがなぜ好まれるか？という話
* Tall Call Optimization の話が出てくるが、これは抽象マシンでプログラムの（空間）計算量を見積もる具体例、と見る方が良い。
	* ここでは格別 TCO が重要なわけではない（実際問題、関数型プログラミングをするなら重要な技法ではあるが）。
* Tail Call Optimization というケーススタディから、ガーベッジコレクションへの流れは大事。
	* 「この例は典型的とはいえない。現実的なプログラムのほとんど全てが、スタックに用意に格納できないような、長期的あるいは共有のデータを多量に持っている。したがって、やはり不要な変数を削除するという一般的な問題を解決しなければならない。」
	* スタックに積めば良いというのはわりかし技術的な（限定的な）解決であり、ガーベッジコレクションが必要
* Active / Inactive / Free の3状態
	* 特になにもしなければ、制御の流れを管理するためのメモリ（意味スタックに対応）は Free になり、データ構造のために使用されるメモリ（格納域に対応）は何もしないと Inactive になる。
* GC がある上でも、以下の点は開発者の責任
	* メモリリークを避けること
		* （宣言的モデルより明示的状態の方がやりやすい）
	* 外部資源を管理すること
		* プログラムから外部資源への参照
		* 外部資源からプログラム内の実体への参照

### 2.6 核言語から実用言語へ

* 手続きから関数への言語抽象が最重要ポイント
* 入れ子マーカ($) はよく理解して手続きの書き方と見比べると良い
* 以下の糖衣構文的な拡張は、Ruby プログラミングでもよく現れている
	* 文を「自然に」式に拡張する
	* andthen / orelse
		* Ruby の `foo if expr` / `bar unless expr` に対応
* Mozart の対話的インターフェースは Ruby より少し優れているところがある
	* 具体的には、以下の結果が Oz と Ruby で変わる
	* `x = 1; pr = Proc.new do println(x); x = 2; pr.call()`
	* この振る舞いが対話的プログラミングをより支援するのはわかる
		* が、意味論的に Ruby に取り入れるのは難しいかなあ

### 2.x 発展

* 単一化の概念は、パターンマッチングのアルゴリズムを想像するために有用
* 動的型付けと静的型付けの話題がとても良い
	* 「経験上、違いは大差ない」

**Comment by Altech** [comment]
### 数学的な基礎

この章は数学の集合論の基礎的な言葉が多少の前提になっているので、以下を知っておくと良いと思った（「本書で」という言葉を使っていない箇所は、一般的な集合論の言葉）。

* 集合：何かしらのものの集まり。通常、重複はない。
	* `{1, 2, …. }` のように書く。
	* 名前をつける場合、普通 `E` や`CE` のように大文字で書かれる。
	* 空の集合は、普通 `φ` （ファイ）という記号が使われる。
	* 上記の集合を `X` としたとき、`x ∈ X` と書いたとき、`x` は `X` に含まれるものの一つを意味する。
* 和集合：集合演算の一つ。中置演算子`∪` で書かれる
* 積集合：集合演算の一つ。中置演算子`∩` で書かれる。
* 写像：ある集合の値から別のある集合の値への対応関係
	* 本書では、例えば`{ x -> 1, y -> 1 }` のように集合っぽい記法を使って書かれれているが、ここは要注意。
	* 実際、だいたい集合みたいなものだと思っておいて問題ないが、厳密に言うと違うし、「ある集合の値から別のある集合の値への対応関係」という風にちゃんと理解しておくと方が混乱が少ないはず。
			* 例えば、以下は集合とはみなせるが、写像としてはおかしい。写像として`x`に対応する値が何なのか分からないため。
				* `{ x -> 1, x -> 2 }`
			* 本書で出てくる、いかにも和集合として定義できそうな以下の操作が、「添加」として和集合と区別されているのはこのため。
				* ○: `E + { x -> 2 }`
				* ×: `E ∪ {x -> 2 }`
	* 本書で定義される環境(environment) は写像の一種。
		* 変数識別子から変数への写像が環境。
* 写像に対して、定義域(domain)と値域(?) が定義できる。
	* 一個上の例だと、定義域は `{x, y}`、値域は `{1}`
	* この言葉を使うと、「定義域が変数識別子（の集合）で、値域が変数（の集合）であるような写像が環境である」と言える。
* 写像はとりあえず関数という概念と同じだと思って間違いはない。
	* 故に、`E = { x -> 1, y -> 2 }` という写像 `E` に対して：
		* `E(x)` (結果は1) のような関数呼び出しで使われる記法が定義されている。
	* 余談だが、Haskell はこういった数学的な基礎に忠実な言語デザインで、`toStr :: Int -> String`  のように関数 `toStr` の型が書ける。
		* したがって、変数識別子の型を `Id` 、変数の型を `Var` とすると、
			* `E :: Id -> Var` と関数（=写像）を定義でき、`E(id)` のようにして特定の変数識別子に対応する変数を取り出せる。これは上で定義した操作そのもの。

**Comment by miliya612** [comment]
前回 @Altech さんにはお伝えしましたが、本日出張とぶつかってしまったため、欠席とさせてください。
下記、所感を簡単にまとめておきます。

<details>
<summary>感想・疑問</summary>
<pre>
<code>
- 2.1.1 EBNF
    - 終端記号: token。展開の余地がこれ以上なく、解釈後の文法の末尾になりうるもの
    - 非終端記号: 文法規則。任意の終端記号に置き換えられるもの
- 2.1.2 言語の意味
    - linguistic abstractionとsyntax sugar
    - kotlinのExtensionsはlinguistic abstractionのレベルで言語設計を変更しうるのでは？
    - kotlinがJavaの代替品として振る舞う上で、企業における導入を考えた際、**ある程度誰でも読めて書ける** という(少なくとも弊社での)Java導入のメリットをどこまで射程に入れて考えるか
- 2.2 単一代入格納域
    - 用語整理したい
    - 変数がたくさん入っている箱たち: **格納域**
        - **単一代入格納域** の中には、1つの値としか束縛できない変数がいくつか入る。変数と値は1対1で紐付いている
            - あえてセル格納域や値格納域を使用しなかった
                - 部分値について計算するため
                - 宣言的並行性を保つため
                - 関係プログラミングと制約プログラミングの要求のため
        - 値が変更しうる(immutable)変数は、一時的な保存場所となる **セル格納域** が必要
        - **値格納域** の中の変数は、すべてが値に束縛されている
    - 単一の変数
        - 単一代入格納域の中の変数１つ１つは、特に **宣言的変数** もしくは **データフロー変数** と呼ばれる。
- 2.3.4 レコードと手続き
    - レコードの協力な支援のため可能になるGUIプログラミング
        - AndroidやFlutterを例に考える。Androidの場合、GUI(View)要素は基本的にはXMLを使用して記述する。一方、AnkoといったライブラリやFlutterの場合、"プログラミング言語"でGUIを記述することになる。GUIにおける基本要素はWidgetとして扱われ、それらに属性を与えることで描画の際の特性を与えるといった現在の構造は、レコードのサポートが不可欠である。
- 2.4.1 基本概念
    - 動的スコープが有用なのは、他のコンピュータへある手続きのコードを転送するとき
    - 転送先の変数定義(環境変数？)を参照して実行した方が効率が良い場合がある
    - 脚注; ターゲットマシン上で操作が同様に振る舞うという保証がないため、静的スコープであるべき
    - 結局どっち？
    - マルチコンテナ間の通信など、通常オーケストレーションツールで隠蔽されている点にも該当する話かも
</code>
</pre>
</details>

**Comment by Altech** [comment]
次回 👉  https://github.com/wantedly/ctmcp-reading/issues/5
