### ISSUE TITLE
第三章 宣言的プログラミング技法 (2/5)

### ISSUE THREAD

**Issue by Altech** [wantedly/ctmcp-reading#5]
## 当日まで

* 各自読む
* できれば感想や疑問点をここに書くか、別イシューを紐付ける
* できれば練習問題も解く

## 当日

* 持ち回りで輪講(45min) @kdnk  
* 疑問点や感想を事前のイシューで各自まとめて、ディスカッション(30min)
* 練習問題（これもやったものは事前にリポジトリに Push or このイシューに紐付ける）(45min)
* 次の輪講の担当を決める

cc: @wantedly/ctmcp-readers @miliya612

**Comment by Altech** [comment]
読んだので気になったところや良いこと言ってるなと思ったことを雑メモ。

## 第三章

* 宣言的プログラミングはなぜ重要か？
	* 「関数プログラミングはなぜ重要か(1984)」という文章が有名だけど、本章は他の枠組みとも相対化されていて、これよりかなり明快だと思った
		* https://www.sampou.org/haskell/article/whyfp.html
* 注：
	* 定義的見方と観察的見方
		* 例えば、Ruby でも宣言的に振る舞うコンポーネントは作成できる
			* Ruby でも純粋関数的に振る舞うコンポーネントを作成できる
	* 「しばしば、密接な相互作用が必要となる。…しかし、重要な原則は、そういう密接な相互作用は必要なときに限って使うべきであり、必要がなければ使うべきではない、ということである。この原則を守るために、できるだけ多くのコンポーネントを宣言的にすべきである。」
* 仕様記述言語
	* 

### 3.2 反復計算

* ポイント：局所的手続きの使い方
	* 私見：字句的スコープを参照可能な関数／手続きを第一級のデータ型としている全ての言語で、この手の設計判断が必要になる。
		* 字句的スコープを使えば引数は減らせるが、それは明快か？
* ポイント：手続き値を使った公開プログラミング
	* ニュートン法という具体例から、反復計算 `Iterate` への一般化
	* while ループの実装

### 3.3 再帰計算

* 反復計算は再帰計算の限定されたモデル
	* 再帰計算は、末尾に限らず自身を呼べる。
		* => 呼んでから戻ってきて計算したりもできるので、スタックが一定となる保証はない。
* 階乗関数の定義からそれが明らかになる
	* 再帰的定義を反復的定義に落とし込むという非自明な問題が生まれる

### 3.4 再帰を用いるプログラミング

* 再帰的なデータ型の定義
	* これはできるようになっておくべき・・。
	* 例題：ActiveRecord の `includes` の引数として許容される値を文脈自由文法の形で再帰的に定義せよ。
		* 注：前章で用いた糖衣構文の概念を使うと簡潔になる
	* 例題：UsersService の update API のリクエストボディを再帰的に定義せよ。
* 良いこと言ってる。
	* 「これは、関数を定義する一般的技法の例である。どの文も、定義域に属さない値を渡されたら必ず例外が発生するようにせよ。そうしておくと、定義域に属さない値を引数として呼ばれた時、関数全体として例外を発生する機会が最大になるからである。」
* 「ここには学ぶべき重要な教訓がある。ある型を使う再帰的関数を書く前に、その型の再帰的定義を描かなければならない。」
* アキュムレータ
	* 計算＝情報を処分すること
	* 処分された情報が（暗に）蓄積されているので、「アキュムレータ」
	* こういう情報処理を行うのが五章の明示的状態モデル
		* よって、アキュムレータが増えたら明示的状態の方が適している可能性が高い
* リスト、キュー、木
	* 状態ありモデルで教えられることが多いが、多くの技法は宣言的モデルの範囲で説明できる
	* 一方で、状態がないと（計算量的に）厳しいケースがどうしてもある、というのも注意。
	* 私見：おそらく、差分リストという論理型プログラミング由来の概念が最も難しい
		* 「未束縛の値」「一度だけ束縛できる」という性質を利用して、リストの末尾を1ステップで書き換える
			* とはいえ、ここまで難しいことやるなら明示的状態を使いたいというのが普通の感想だと思う。
			* ただし、9章の関係プログラミングまで行ってから戻ってくると、ここらへんの深い動機はわかる
				* 関係（＝論理的な表明）というものが問題によってはうまく働くこと

### 3.3 時間効率と空間効率

* 時間計算量と空間計算量
	* それらを形式的に推論する方法
* 時間計算量
	* 最悪時計算量と償却的計算量
* 空間計算量（メモリ使用量）
	* 瞬間アクティブメモリ量
	* 瞬間メモリ消費量／総メモリ使用量

### 3.4 高階プログラミング

* 盛りだくさん
	* ここはまあ普通に関数型っぽい話。
* * 宣言的ループと命令的ループの違いみたいは話は、現代風にいえばGolang のループ変数が goroutine で参照するとバグるみたいな有名な落とし穴になる

### 3.5 抽象データ型

* ソフトウェアエンジニアリング的に知っておくと良い概念
* 抽象データ型の実装を行なった上で、内部構造を隠蔽したいという話になる
	* なぜインターフェースと実装を分離することが重要かと言ったことが超明快に説明されている
* プログラミング言語レベルでそれを支援するための原始的機構
	* 名前生成と名前比較
	* （そう考えるとリフレクションまみれの Ruby って結構危うい…）
* 資格とセキュリティ
	* 最小特権原則

### 3.6 宣言的でない必要物

Skip.

### 3.7 小規模プログラム設計

* 「（規模の違いは）ソースコードの行数で表されるプログラムの大きさとは何の関係もなく、その開発に何人携わったかに関係する。…現在のある人と、1年後の同じ人は2人と考える。人は一年経つと多くの細々としたことを忘れるからである。」名言っぽい
* ソフトウェアコンポーネントという概念
* それを支援するためのモジュール・ファンクターという言語抽象

**Comment by Altech** [comment]
過去に実際にあったプログラミング事項や現実に抱えている課題で本章の内容に合致するものをそれなりに思いついたので、章末問題のノリで書き下してみた。

#### 再帰的なデータ型の定義と、再帰関数に関して

`ActiveRecord::Relation` の `includes(data)` 指定に対して、対象となるアソシエーションを数えるプログラム `collect_assoc(data)` を書け（ヒント：糖衣構文の考え方を利用して単純化された入力の型を定義した上で、再帰関数を書くと良い）。

#### 資格とセキュリティに関して

Wantedly People の名刺情報は個人情報であるため、プログラムのバグによって意図せずユーザーをまたいで情報が渡ってしまうことは避けたい。しかし、ActiveRecord を素朴に利用した場合、user_id にうっかり違うものを渡してしまえば、情報が流出してしまう。本書の稼働値や名前の考え方を用いて、API において意図せずそういったことが起きないための機構を考案せよ。

**Comment by Altech** [comment]
## 場所

今日は5階でやります！

**Comment by kdnk** [comment]
https://paper.dropbox.com/doc/ctmcp03--AW~FSS9sFtgopR_N7r2k7BvGAg-txLBrlUhbd0rdDU6tptaO

**Comment by nekootoko3** [comment]
## 個人的なメモ @nekootoko3 

よく分からなかったところは`??`がついている。

<details>
<summary>メモ</summary>
## 宣言的プログラミング技法

### 3章の内容

# [TODO]

- 定義
  - 3.1 宣言的とはどういうことか？
- 再帰を用いるプログラミング
  - 3.2 反復計算
  - 3.3 再帰計算
  - 3.4 再帰を用いるプログラミング
- 抽象化
- 現実世界
  - 3.5 時間効率と空間効率
  - 3.6 高階プログラミング
- 3.7 抽象データ型
- 3.8 宣言的でない必要物

### 宣言的プログラミングの2つの重要な性質

- 合成的であること
  - 他コンポーネントや自身の呼び出しとは無関係にテストしたり正しさを証明できる
    - コンポーネントとは、きちんと定義された入力と出力を持つ、正確に範囲が定められたコンポーネント片
    - プログラム全体を理解する労力は各コンポーネントの和になる
      - 他コンポーネントとの依存関係や自身の過去の呼び出しを考慮した場合の労力はより大きい
        - コンポーネント間に親密な相互作用が存在する例としては、共有状態を持つ並列的プログラムがある
    - 他に依存しない、明示的状態を持たないため?
- 推論が容易であること
  - 他の表現力豊かなモデルと比較して容易
  - 値についてだけ計算するので、単純な代数的・論理的推論技術が使える
- 代数学の標準規則「等しいものは等しいもので置き換えることができる」
  - = 参照透過性
  - 関数は引数のみに依存する
- 宣言的プログラミングの基本
  - 高階プログラミングを使ってプログラム構造を単純化し、プログラムを再帰的関数定義の集合と見なすこと

## 宣言的とはどういうことか

### 宣言的プログラミングの分類

```
宣言的プログラミング
├ 記述的
└ プログラム可能
  ├ 観察的
  └ 定義的
    ├ 宣言的モデル
    ├ 関数型プログラミング
    └ 論理型プログラミング
```

#### 記述的宣言性

- 最も表現力が乏しい
- レコードの定義しかできない
- 一般的なプログラムは書けないが、処理しやすいデータ構造になる
  - e.g. htmlといった整形言語、xmlといった情報交換言語

#### プログラム可能な宣言性

チューリングマシンと同等の表現性を持つ
つまり、任意のコンピュータでプログラム可能な任意は表現できる

- 2つの見方
  - 観察的見方
    - 宣言性をコンポーネントインターフェースの1つの性質と見る。振る舞いにだけ関心を持つ
    - 内部実装が宣言的計算モデルに従って書かれていなくても、独立で、状態なしで、決定的に書かれていればよい。
  - 定義的見方
    - 宣言性をコンポーネント実装の1つの性質として見る

- 仕様記述言語
  - 仕様と実装を区別しない
  - DSLのこと??
  - 定理証明器??

#### 宣言的モデルのコンポーネント実装

- 宣言的モデルの基本操作は全て宣言的(基本操作って、変数束縛とか、?)
- 宣言的操作を宣言的モデルの要素と組み合わせると宣言的操作になる
  - 宣言的モデルの要素である複合文
    - 文の列
    - local文
    - if文
    - case文
    - 手続き定義
  
### 反復計算

- 初期状態S0から出発して、後続ステップの状態を更新して最終状態Sfinalに到達すること

```
S0 -> S1 -> ... -> Sfinal
```

- 一般的図式
  - whileと同様の制御

```
fun {Iterate Si}
  if {IsDone Si} then Si
  else Si+1 in
    Si+1={Transfrom Si}
    {Iterate Si+1}
  end
end
```

- 補助ルーチンの定義をそれを必要とするルーチンの中に入れるかはトレードオフ
  - 中に入れると主ルーチンの引数を外部参照できるので、補助ルーチンの引数が少なくなる
    - 一方で主ルーチンが呼ばれるたびに補助ルーチンが新たに生成される
  - 外に出すと、主ルーチンが何回呼ばれても手続き値が生成されるのは一回だけで済む
    - 補助ルーチンの引数は増える

#### 一般図式から制御抽象へ

- 他のコンポーネントで使えるプログラムコンポーネントとしての一般的図式を用意する = `制御抽象`
  - 上記一般的図式では {IsDone X} {Transform X} はユーザーが定義する必要のある手続き
  - ユーザーが定義する手続きを高階プログラミングを用いて引数化することで制御抽象にする

```
fun {Iterate Si IsDone Transform}
  if {IsDone Si} then Si
  else Si+1 in
    Si+1={Transfrom Si}
    {Iterate Si+1 IsDone Transform}
  end
end
```

### 再帰計算

#### 2つの再帰計算

- 関数
  - 自分自身を呼び出しているケース
    - 反復計算は再帰計算の特殊ケース
- データ型
  - 自分自身に基づいて定義しているケース
    - リストはより小さいリストに基づいて定義している

#### 代入ベースの抽象マシン

- 意味表明中の変数識別子を変数に置き換える = `代入`
- 識別子に格納域実体を直接代入するので環境が存在しない
- 環境ベースの抽象マシンは現実のコンピュータの実装に忠実
  - 一方で環境によって間接化が進み、手計算が煩雑になる
- 代入ベースの抽象マシンは扱う記号が少ないので手計算には便利
  - 一方で実装が煩雑なので現実で採用されることは少ない

#### リストについてのプログラミングの基本的技法

- 再帰的に考える
  - 基本の場合、小さなリスト(e.g. 要素がないかあっても1つか2つのリスト)について答えを直接計算する
  - 再帰の場合、大きなリストについては、要素が1つ以上少ない結果のリストに基づいて計算する
- 再帰計算を反復計算に変換する
  - 単純な再帰計算は再帰回数に比例して意味表明スタックが増大することが多い
    - 状態変換の列にすることで作り直すことで末尾呼び出し最適化を実現し効率的な実行を実現する
    - 補助ルーチンを使う時、元の関数が呼び出されるたびに補助スコープが作り直されないようスコープに注意する
- 状態不変表明による正しさ
  - 特定の状態に関して計算を行って中間状態について推測を行うこと
- 型をなぞってプログラムを構成する
  - ある型の再帰的関数を書く前にその型の再帰的定義を書かなければならない
    - 見かけ上簡単な、誤った関数に騙される原因になる
      - e.g. 型のリストのみを引数に取るのか、型自体を引数に取ることもできるのか
    - 型推論は再帰的な型が正しく使われているかの検証にはなるが、再帰的な型の設計はプログラマの責任

#### アキュムレータ

- 現実的な宣言的プログラミングは最初から反復形で書かれる
  - 状態を常に先送りにすることで戻ってきてからの計算を避ける
- 入れ子の手続き呼び出しを通じて状態をスレッド化??
  - アキュムレータプログラミング??
- 複数アキュムレータを必要とする場合には、明示的状態を使うことでプログラムを単純にできる


### 実行時間と空間効率

#### 実行時間

- 定数倍を無視した実行時間
  - 最悪時間計算量とも
    - e.g. MergeSort は nlogn
  - 定数因子を定めることは難しい
    - 複雑なハードウェアとソフトウェアを持っているから
      - メモリ管理、パイプライン、コンテクストスイッチ等

#### メモリ使用量

- 瞬間アクティブメモリ消費量
  - プログラムの実行に必要なメモリ量
    - こちらの方が重要
- 瞬間消費メモリ量
  - プログラムに割り当てられるメモリ量

- 償却的計算量

### 高階プログラミング

#### 基本操作

高階プログラミングの全ての技法の基となる4つの基本操作

- 手続き抽象
  - 任意の文を手続き値(閉包)に変換する能力
  - 手続き値は文脈的環境を含んでいるので、パッケージ化した文を実行するのと同じ結果が得られる
- 汎用性
  - 手続き呼び出しの引数として手続き値を呼び出す能力
    - 本体の任意の特定の実体(任意の操作または値)を関数の引数にする
      - FoldLeftとかそういうやつ
- 具体化
  - 手続き呼び出しの結果として手続きを返す能力
- データ構造の中に手続き値を入れる能力
  - 複数の使いみちがある
    - 明示的遅延計算(??)
      - 一度に完全なデータ構造を作らず必要に応じて作るという考え方
    - モジュール
      - 関連する操作の集合を持つレコード
    - ソフトウェアコンポーネント(??)
      - 次のように考えられる
        - 汎用手続き
        - モジュールの集合を入力引数として新しいモジュールを返す
        - あるモジュールをそれが必要とするモジュールによって規定する

#### ループ抽象

- 宣言的ループと命令的ループ
  - 宣言的ループ
    - 反復のたびに新しい変数が宣言される
      - 処理がスレードでも問題ない
  - 命令的ループ
    - ループカウンタは代入可能な変数
      - 反復のたびに異なる値が代入される
        - 処理がスレッドになると問題になる可能性がある

#### データ駆動技法

- `Map`も`Filter`も`FoldRight`で表現できる
  - `FoldRight`はアキュムレータつきのforループ

#### 明示的遅延計算

- `demand-driven execution`
  - リストなど、データが必要になった時に構築する
- `supply-driven execution`
  - 要素が必要か否かにかかわらすリスト全体を用意する

#### カリー化

- n引数の関数の代わりに、1引数のn重の入れ子の関数を書こうという考え方

### 抽象データ型

ADT(Abstraction Data Type)

- データ型とか型といわれるものは、値の集合とそういう値に対する操作の集合を一緒にしたもの
- ある型が実装とは無関係にその操作の集合で完全に定義されている場合、その型は抽象的であるという(`抽象データ型`)
  - go の interface ??
- 線形リストを使った辞書の実装
  - キーの降順にソートされたキーとバリューのペアの線形リスト
  - get・put ともに 最悪時でO(n)の時間がかかるので効率的ではない
- 木構造を使った辞書の実装
  - O(logn)となり効率がいい
- 状態ありで実装するとO(1)となりさらに効率がいいらしい
- 値の内部表現が見えていることは2つの意味で危険(??正直あまりピンときていない)
  - 保守的な面
    - e.g. プログラムの実装を変えようとしたとき、エラー捕捉の問題。
  - セキュリティ的な面
- ADTの値の内部表現を干渉から守る2通りのやり方(??)
  - 停留値
  - 可動値
- 値を保護する1つの方法として、キーを使って値をラップする方法が挙げられる
  - 新しい名前を関数を用意し(その名前は一意であるということが保証されていることから状態あり)、その名前を通じてのみ値にアクセスできないようにする
    - ラッパーとアンラッパーを用意し、入ってくる値をアンラップし、出ていく値をラップする
      - 内部表現が外から見えなくなることで安全性が高まる
      - 安全なADTはそれぞれのラッパ＝とアンラッパーを持つ()

### 資格とセキュリティ

- プログラミング言語の内に潜む敵からの攻撃に耐えるようなプログラムを構築できる性質を持つものを「安全な」プログラミング言語という
- `資格`とは、偽造不能の言語実体で、その所有者に一群の操作を実行する権利を与えるもの
  - 言語実体(?? 特定のプログラミング言語における内部表現、さらに言えばデータ型のこと ??)
    - e.g. ラップ(seal)された値は、そのKey(言語実体)の所有者でなければ、アンラップ(unseal)してその値を知ることはできない ??
- 宣言的モデルにおける資格は、権利を与えるアクションの集合を変化させられないことが問題
  - 明示的状態が必要
  - ある状態ではある関数の実行を行えない、というようなこと(?? 例が分からない。空のスタックをPopするならnilを返すとかそういう話ではなさそう ??)
- `最小特権`(least priviledge)
  - 知る必要(need to know)の原則
  - 安全なシステムを構築するのに必要な原則
  - 各実体はその実行に必要な最小限の権利を与えられるべき
    - 最小は分からないので近似値でよい

### 宣言的でない必要物

#### 小規模プログラム設計

##### 設計方法

1. 形式張らない仕様
  - できるだけ正確な言葉で仕様を書く
    - 特に入出力に関してその定義まで明らかにする
    - 形式的でないというのは、数学的ではないという意味で乱雑に書いていいというわけではない
2. 調査
  - プログラムに必要となりそうなプログラム片を対話的インターフェースで確認する
    - これによってプログラムの構造がはっきりしてくる
3. 構造とコーディング
  - 入力から出力を計算する操作と、それらのまとめ方の大まかな輪郭を作る
  - それからプログラムを埋めるコードを書く
    - 操作は単純でなければならない
    - どの操作も1つのことを行わなければならない
4. テストと推論
  - テストによって上手くいかないケースを修正する
  - 明らかでない部分については推論する
5. 品質の判定
  - 設計の品質を判定する
    - `単純である`ということが最も重要
      - 単純さは、効率性、拡張性、保守性などその他の必要要素を達成するのが容易になる
    - 次にプログラムの完全性が重要

#### ソフトウェアコンポーネント

- プログラムを組織化するよい方法は論理的単位に分割すること
  - 論理的単位とは、何らかの関係のある操作の集合を実装したもの
  - 論理的単位はインターフェースと実装という2つの部分から成っており、外から見えるのはインターフェースだけ
- こうすることでプログラムは有向グラフになる
<details>

**Comment by miliya612** [comment]
https://github.com/miliya612/ctmcp-reading/blob/master/03_declarative_programming_techniques/memo.md

**Comment by Altech** [comment]
👉  第四章 宣言的並行性 (2/19) #6
