### ISSUE TITLE
第五章 メッセージ伝達並行性

### ISSUE THREAD

**Issue by Altech** [wantedly/ctmcp-reading#7]
## 当日まで

* 各自読む
* できれば感想や疑問点をここに書くか、別イシューを紐付ける

## 当日

* 持ち回りで進める(45min) @kdnk 
* 疑問点や感想を事前のイシューで各自まとめて、ディスカッション(45min)
* 次の輪講の担当を決める

cc: @wantedly/ctmcp-readers @miliya612

**Comment by miliya612** [comment]
https://github.com/miliya612/ctmcp-reading/blob/master/05_message_passing_concurrency/memo.md

**Comment by Altech** [comment]
全体的にかなり有益な議論ができてよかった 🎉 

![DSC_0211](https://user-images.githubusercontent.com/1248994/54609730-e213a980-4a96-11e9-8dc8-5e1c4f0d7c2e.JPG)

**Comment by Altech** [comment]
next: https://github.com/wantedly/ctmcp-reading/issues/8
