### ISSUE TITLE
第7章 オブジェクト指向プログラミング (4/16)

### ISSUE THREAD

**Issue by kdnk** [wantedly/ctmcp-reading#9]
## 当日まで

* 各自読む
* できれば感想や疑問点をここに書くか、別イシューを紐付ける

## 当日

* 持ち回りで進める(45min) @kdnk
* 疑問点や感想を事前のイシューで各自まとめて、ディスカッション(45min)
* 次の輪講の担当を決める

cc: @wantedly/ctmcp-readers @miliya612

**Comment by miliya612** [comment]
https://github.com/miliya612/ctmcp-reading/blob/master/07_object_oriented_programming/memo.md

**Comment by Altech** [comment]
今回のディスカッションのサマリ「Matzはすごい」

📝 次回は3週間後の5/7に行う。

次 https://github.com/wantedly/ctmcp-reading/issues/10
